### ISSUE TITLE
BUG - Package Fails to Run on Spark Databricks

### ISSUE THREAD

**Issue by vincentkoc** [fivetran/dbt_facebook_ads_creative_history#13]
**Are you a current Fivetran customer?** 
Vincent, Head of Data Science at Oroton

**Describe the bug**

Currently using the DBT package in a new vanilla DBT build on version 0.20.0

```
(env) (base) ~ dbt --version
installed version: 0.20.0
   latest version: 0.20.1

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 0.20.0
  - snowflake: 0.20.0
  - redshift: 0.20.0
  - postgres: 0.20.0
  - spark: 0.20.0
```

I'm running this on Azure Databricks using the spark sql setup and have also installed the Spark SQL module and add the dispatcher to my config.

```  dbt found two resources with the name "stg_facebook_ads__carousel_media". Since these resources have the same name,
  dbt will be unable to find the correct resource when ref("stg_facebook_ads__carousel_media") is used. To fix this,
  change the name of one of these resources:
  - model.facebook_ads_creative_history.stg_facebook_ads__carousel_media (models/snowflake/stg_facebook_ads__carousel_media.sql)
  - model.facebook_ads_creative_history.stg_facebook_ads__carousel_media (models/bigquery/stg_facebook_ads__carousel_media.sql)
```

**Steps to reproduce**
Add package and run on DBT 0.20.0 on Azure Databricks

**Expected behavior**
No error to 

**Project variables configuration**

```yml
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'oroton_dbt_databricks'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'databricks_cluster'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

vars:
    ad_reporting__pinterest_enabled: False
    ad_reporting__microsoft_ads_enabled: False
    ad_reporting__linkedin_ads_enabled: False
    ad_reporting__google_ads_enabled: True
    ad_reporting__twitter_ads_enabled: False
    ad_reporting__facebook_ads_enabled: True
    ad_reporting__snapchat_ads_enabled: False
    facebook_ads_schema: silver_fivetran_facebookads
    facebook_ads_database: silver_fivetran_facebookads
    google_ads_schema: silver_fivetran_adwordsspark
    google_ads_database: silver_fivetran_adwordsspark

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
    # disable both pinterest models if not using pinterest ads
    pinterest:
        enabled: false
    pinterest_source:
        enabled: false

    # disable both microsoft ads models if not using microsoft ads
    microsoft_ads:
        enabled: false
    microsoft_ads_source:
        enabled: false

    # disable both linkedin ads models if not using linkedin ads
    linkedin:
        enabled: false
    linkedin_source:
        enabled: false

    # disable both twitter ads models if not using twitter ads
    twitter_ads:
        enabled: false
    twitter_ads_source:
        enabled: false

    # disable all three facebook ads models if not using facebook ads
    facebook_ads:
        +schema: fivetran_general
        enabled: true #IF YOU ARE USING FACEBOOK, DELETE THIS CONFIG, DO NOT SIMPLY SET TO TRUE
    facebook_ads_source:
        +schema: fivetran_general
        enabled: true #IF YOU ARE USING FACEBOOK, DELETE THIS CONFIG, DO NOT SIMPLY SET TO TRUE
    facebook_ads_creative_history:
        +schema: fivetran_general
        enabled: true #IF YOU ARE USING FACEBOOK, DELETE THIS CONFIG, DO NOT SIMPLY SET TO TRUE

    # disable both google ads models if not using google ads
    google_ads:
        +schema: fivetran_general
        enabled: true
    google_ads_source:
        +schema: fivetran_general
        enabled: true

    # disable both snapchat ads models if not using snapchat ads
    snapchat_ads:
        enabled: false
    snapchat_ads_source:
        enabled: false%
```

**Package Version**

```yml
packages:
  - package: fivetran/ad_reporting
    version: 0.4.0
  - package: dbt-labs/dbt_utils
    version: 0.7.1
  - package: dbt-labs/spark_utils
    version: 0.2.2
  - package: fivetran/facebook_ads
    version: 0.3.0
```

**Warehouse**

 
- [ ] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [ ] Postgres
- [x] Databricks
- [ ] Other (provide details below)

**Additional context**
 

I patched just by removing all the folders and keeping the Spark SQL modules and seems to work. But this will break as soon as i update or run on a CI/CD workflow

**Screenshots**

**Please indicate the level of urgency** 

Unable to go-live with my purchase of Fivetran

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [x] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.
